debug = true

[database]
ilp = "tcp::addr=localhost:9009;protocol_version=2;username=test_ilp_user;token=NPo-BO1F2zr7LoWBEeBpY6ZfNQXRdhpyud3llmWUycg;token_x=ayc3ehklyXSa4Pe1w-jVxqGZjh0jJMUECThWftnHnu0;token_y=N0fRjqck8MrwcvLCuJK_lQexLaDV8ZSn-EKnNHsBX1o"
pgsql = "host=localhost port=8812 user=test_user password=pass dbname=qdb"

[tables.metrics1]
schema = [
    ["timestamp", "Timestamp"],
    ["col1", "Double"],
    ["col2", "Long"],
    ["col3", "Symbol"],
    ["col4", "Double"],
    ["col5", "Long"],
    ["col6", "Symbol"],
    ["col7", "Double"],
    ["col8", "Long"],
    ["col9", "Symbol"],
    ["col10", "Double"],
    ["col11", "Long"],
    ["col12", "Symbol"],
    ["col13", "Double"],
    ["col14", "Long"],
    ["col15", "Symbol"],
    ["col16", "Double"],
    ["col17", "Long"],
    ["col18", "Symbol"],
    ["col19", "Double"],
    ["col20", "Long"],
    ["col21", "Symbol"],
    ["col22", "Double"],
    ["col23", "Long"],
    ["col24", "Symbol"],
    ["col25", "Double"],
    ["col26", "Long"],
    ["col27", "Symbol"],
    ["col28", "Double"],
    ["col29", "Long"],
    ["col30", "Symbol"],
    ["col31", "Double"],
    ["col32", "Long"],
    ["col33", "Symbol"],
    ["col34", "Double"],
    ["col35", "Long"],
    ["col36", "Symbol"],
    ["col37", "Double"],
    ["col38", "Long"],
    ["col39", "Symbol"],
    ["col40", "Double"]
]
designated_ts = "timestamp"

[tables.metrics1.send]
batch_pause = ["50ms", "100ms"]
batch_size = [5000, 10000]
parallel_senders = 16
tot_rows = 15_000_000
batches_connection_keepalive = 20

[tables.metrics2]
schema = [
    ["timestamp", "Timestamp"],
    ["col1", "Double"],
    ["col2", "Long"],
    ["col3", "Symbol"],
    ["col4", "Double"],
    ["col5", "Long"],
    ["col6", "Symbol"],
    ["col7", "Double"],
    ["col8", "Long"],
    ["col9", "Symbol"],
    ["col10", "Double"],
    ["col11", "Long"],
    ["col12", "Symbol"],
    ["col13", "Double"],
    ["col14", "Long"],
    ["col15", "Symbol"],
    ["col16", "Double"],
    ["col17", "Long"],
    ["col18", "Symbol"],
    ["col19", "Double"],
    ["col20", "Long"],
    ["col21", "Symbol"],
    ["col22", "Double"],
    ["col23", "Long"],
    ["col24", "Symbol"],
    ["col25", "Double"],
    ["col26", "Long"],
    ["col27", "Symbol"],
    ["col28", "Double"],
    ["col29", "Long"],
    ["col30", "Symbol"],
    ["col31", "Double"],
    ["col32", "Long"],
    ["col33", "Symbol"],
    ["col34", "Double"],
    ["col35", "Long"],
    ["col36", "Symbol"],
    ["col37", "Double"],
    ["col38", "Long"],
    ["col39", "Symbol"],
    ["col40", "Double"]
]
designated_ts = "timestamp"

[tables.metrics2.send]
batch_pause = ["50ms", "100ms"]
batch_size = [5000, 10000]
parallel_senders = 16
tot_rows = 15_000_000
batches_connection_keepalive = 20

[tables.metrics3]
schema = [
    ["timestamp", "Timestamp"],
    ["col1", "Double"],
    ["col2", "Long"],
    ["col3", "Symbol"],
    ["col4", "Double"],
    ["col5", "Long"],
    ["col6", "Symbol"],
    ["col7", "Double"],
    ["col8", "Long"],
    ["col9", "Symbol"],
    ["col10", "Double"],
    ["col11", "Long"],
    ["col12", "Symbol"],
    ["col13", "Double"],
    ["col14", "Long"],
    ["col15", "Symbol"],
    ["col16", "Double"],
    ["col17", "Long"],
    ["col18", "Symbol"],
    ["col19", "Double"],
    ["col20", "Long"],
    ["col21", "Symbol"],
    ["col22", "Double"],
    ["col23", "Long"],
    ["col24", "Symbol"],
    ["col25", "Double"],
    ["col26", "Long"],
    ["col27", "Symbol"],
    ["col28", "Double"],
    ["col29", "Long"],
    ["col30", "Symbol"],
    ["col31", "Double"],
    ["col32", "Long"],
    ["col33", "Symbol"],
    ["col34", "Double"],
    ["col35", "Long"],
    ["col36", "Symbol"],
    ["col37", "Double"],
    ["col38", "Long"],
    ["col39", "Symbol"],
    ["col40", "Double"]
]
designated_ts = "timestamp"

[tables.metrics3.send]
batch_pause = ["50ms", "100ms"]
batch_size = [5000, 10000]
parallel_senders = 16
tot_rows = 15_000_000
batches_connection_keepalive = 20

[tables.metrics4]
schema = [
    ["timestamp", "Timestamp"],
    ["col1", "Double"],
    ["col2", "Long"],
    ["col3", "Symbol"],
    ["col4", "Double"],
    ["col5", "Long"],
    ["col6", "Symbol"],
    ["col7", "Double"],
    ["col8", "Long"],
    ["col9", "Symbol"],
    ["col10", "Double"],
    ["col11", "Long"],
    ["col12", "Symbol"],
    ["col13", "Double"],
    ["col14", "Long"],
    ["col15", "Symbol"],
    ["col16", "Double"],
    ["col17", "Long"],
    ["col18", "Symbol"],
    ["col19", "Double"],
    ["col20", "Long"],
    ["col21", "Symbol"],
    ["col22", "Double"],
    ["col23", "Long"],
    ["col24", "Symbol"],
    ["col25", "Double"],
    ["col26", "Long"],
    ["col27", "Symbol"],
    ["col28", "Double"],
    ["col29", "Long"],
    ["col30", "Symbol"],
    ["col31", "Double"],
    ["col32", "Long"],
    ["col33", "Symbol"],
    ["col34", "Double"],
    ["col35", "Long"],
    ["col36", "Symbol"],
    ["col37", "Double"],
    ["col38", "Long"],
    ["col39", "Symbol"],
    ["col40", "Double"]
]
designated_ts = "timestamp"

[tables.metrics4.send]
batch_pause = ["50ms", "100ms"]
batch_size = [5000, 10000]
parallel_senders = 16
tot_rows = 15_000_000
batches_connection_keepalive = 20

[tables.metrics5]
schema = [
    ["timestamp", "Timestamp"],
    ["col1", "Double"],
    ["col2", "Long"],
    ["col3", "Symbol"],
    ["col4", "Double"],
    ["col5", "Long"],
    ["col6", "Symbol"],
    ["col7", "Double"],
    ["col8", "Long"],
    ["col9", "Symbol"],
    ["col10", "Double"],
    ["col11", "Long"],
    ["col12", "Symbol"],
    ["col13", "Double"],
    ["col14", "Long"],
    ["col15", "Symbol"],
    ["col16", "Double"],
    ["col17", "Long"],
    ["col18", "Symbol"],
    ["col19", "Double"],
    ["col20", "Long"],
    ["col21", "Symbol"],
    ["col22", "Double"],
    ["col23", "Long"],
    ["col24", "Symbol"],
    ["col25", "Double"],
    ["col26", "Long"],
    ["col27", "Symbol"],
    ["col28", "Double"],
    ["col29", "Long"],
    ["col30", "Symbol"],
    ["col31", "Double"],
    ["col32", "Long"],
    ["col33", "Symbol"],
    ["col34", "Double"],
    ["col35", "Long"],
    ["col36", "Symbol"],
    ["col37", "Double"],
    ["col38", "Long"],
    ["col39", "Symbol"],
    ["col40", "Double"]
]
designated_ts = "timestamp"

[tables.metrics5.send]
batch_pause = ["50ms", "100ms"]
batch_size = [5000, 10000]
parallel_senders = 16
tot_rows = 15_000_000
batches_connection_keepalive = 20

[tables.metrics6]
schema = [
    ["timestamp", "Timestamp"],
    ["col1", "Double"],
    ["col2", "Long"],
    ["col3", "Symbol"],
    ["col4", "Double"],
    ["col5", "Long"],
    ["col6", "Symbol"],
    ["col7", "Double"],
    ["col8", "Long"],
    ["col9", "Symbol"],
    ["col10", "Double"],
    ["col11", "Long"],
    ["col12", "Symbol"],
    ["col13", "Double"],
    ["col14", "Long"],
    ["col15", "Symbol"],
    ["col16", "Double"],
    ["col17", "Long"],
    ["col18", "Symbol"],
    ["col19", "Double"],
    ["col20", "Long"],
    ["col21", "Symbol"],
    ["col22", "Double"],
    ["col23", "Long"],
    ["col24", "Symbol"],
    ["col25", "Double"],
    ["col26", "Long"],
    ["col27", "Symbol"],
    ["col28", "Double"],
    ["col29", "Long"],
    ["col30", "Symbol"],
    ["col31", "Double"],
    ["col32", "Long"],
    ["col33", "Symbol"],
    ["col34", "Double"],
    ["col35", "Long"],
    ["col36", "Symbol"],
    ["col37", "Double"],
    ["col38", "Long"],
    ["col39", "Symbol"],
    ["col40", "Double"]
]
designated_ts = "timestamp"

[tables.metrics6.send]
batch_pause = ["50ms", "100ms"]
batch_size = [5000, 10000]
parallel_senders = 16
tot_rows = 15_000_000
batches_connection_keepalive = 20

[tables.metrics7]
schema = [
    ["timestamp", "Timestamp"],
    ["col1", "Double"],
    ["col2", "Long"],
    ["col3", "Symbol"],
    ["col4", "Double"],
    ["col5", "Long"],
    ["col6", "Symbol"],
    ["col7", "Double"],
    ["col8", "Long"],
    ["col9", "Symbol"],
    ["col10", "Double"],
    ["col11", "Long"],
    ["col12", "Symbol"],
    ["col13", "Double"],
    ["col14", "Long"],
    ["col15", "Symbol"],
    ["col16", "Double"],
    ["col17", "Long"],
    ["col18", "Symbol"],
    ["col19", "Double"],
    ["col20", "Long"],
    ["col21", "Symbol"],
    ["col22", "Double"],
    ["col23", "Long"],
    ["col24", "Symbol"],
    ["col25", "Double"],
    ["col26", "Long"],
    ["col27", "Symbol"],
    ["col28", "Double"],
    ["col29", "Long"],
    ["col30", "Symbol"],
    ["col31", "Double"],
    ["col32", "Long"],
    ["col33", "Symbol"],
    ["col34", "Double"],
    ["col35", "Long"],
    ["col36", "Symbol"],
    ["col37", "Double"],
    ["col38", "Long"],
    ["col39", "Symbol"],
    ["col40", "Double"]
]
designated_ts = "timestamp"

[tables.metrics7.send]
batch_pause = ["50ms", "100ms"]
batch_size = [5000, 10000]
parallel_senders = 16
tot_rows = 15_000_000
batches_connection_keepalive = 20

[tables.metrics8]
schema = [
    ["timestamp", "Timestamp"],
    ["col1", "Double"],
    ["col2", "Long"],
    ["col3", "Symbol"],
    ["col4", "Double"],
    ["col5", "Long"],
    ["col6", "Symbol"],
    ["col7", "Double"],
    ["col8", "Long"],
    ["col9", "Symbol"],
    ["col10", "Double"],
    ["col11", "Long"],
    ["col12", "Symbol"],
    ["col13", "Double"],
    ["col14", "Long"],
    ["col15", "Symbol"],
    ["col16", "Double"],
    ["col17", "Long"],
    ["col18", "Symbol"],
    ["col19", "Double"],
    ["col20", "Long"],
    ["col21", "Symbol"],
    ["col22", "Double"],
    ["col23", "Long"],
    ["col24", "Symbol"],
    ["col25", "Double"],
    ["col26", "Long"],
    ["col27", "Symbol"],
    ["col28", "Double"],
    ["col29", "Long"],
    ["col30", "Symbol"],
    ["col31", "Double"],
    ["col32", "Long"],
    ["col33", "Symbol"],
    ["col34", "Double"],
    ["col35", "Long"],
    ["col36", "Symbol"],
    ["col37", "Double"],
    ["col38", "Long"],
    ["col39", "Symbol"],
    ["col40", "Double"]
]
designated_ts = "timestamp"

[tables.metrics8.send]
batch_pause = ["50ms", "100ms"]
batch_size = [5000, 10000]
parallel_senders = 16
tot_rows = 15_000_000
batches_connection_keepalive = 20

[tables.metrics9]
schema = [
    ["timestamp", "Timestamp"],
    ["col1", "Double"],
    ["col2", "Long"],
    ["col3", "Symbol"],
    ["col4", "Double"],
    ["col5", "Long"],
    ["col6", "Symbol"],
    ["col7", "Double"],
    ["col8", "Long"],
    ["col9", "Symbol"],
    ["col10", "Double"],
    ["col11", "Long"],
    ["col12", "Symbol"],
    ["col13", "Double"],
    ["col14", "Long"],
    ["col15", "Symbol"],
    ["col16", "Double"],
    ["col17", "Long"],
    ["col18", "Symbol"],
    ["col19", "Double"],
    ["col20", "Long"],
    ["col21", "Symbol"],
    ["col22", "Double"],
    ["col23", "Long"],
    ["col24", "Symbol"],
    ["col25", "Double"],
    ["col26", "Long"],
    ["col27", "Symbol"],
    ["col28", "Double"],
    ["col29", "Long"],
    ["col30", "Symbol"],
    ["col31", "Double"],
    ["col32", "Long"],
    ["col33", "Symbol"],
    ["col34", "Double"],
    ["col35", "Long"],
    ["col36", "Symbol"],
    ["col37", "Double"],
    ["col38", "Long"],
    ["col39", "Symbol"],
    ["col40", "Double"]
]
designated_ts = "timestamp"

[tables.metrics9.send]
batch_pause = ["50ms", "100ms"]
batch_size = [5000, 10000]
parallel_senders = 16
tot_rows = 15_000_000
batches_connection_keepalive = 20

[tables.metrics10]
schema = [
    ["timestamp", "Timestamp"],
    ["col1", "Double"],
    ["col2", "Long"],
    ["col3", "Symbol"],
    ["col4", "Double"],
    ["col5", "Long"],
    ["col6", "Symbol"],
    ["col7", "Double"],
    ["col8", "Long"],
    ["col9", "Symbol"],
    ["col10", "Double"],
    ["col11", "Long"],
    ["col12", "Symbol"],
    ["col13", "Double"],
    ["col14", "Long"],
    ["col15", "Symbol"],
    ["col16", "Double"],
    ["col17", "Long"],
    ["col18", "Symbol"],
    ["col19", "Double"],
    ["col20", "Long"],
    ["col21", "Symbol"],
    ["col22", "Double"],
    ["col23", "Long"],
    ["col24", "Symbol"],
    ["col25", "Double"],
    ["col26", "Long"],
    ["col27", "Symbol"],
    ["col28", "Double"],
    ["col29", "Long"],
    ["col30", "Symbol"],
    ["col31", "Double"],
    ["col32", "Long"],
    ["col33", "Symbol"],
    ["col34", "Double"],
    ["col35", "Long"],
    ["col36", "Symbol"],
    ["col37", "Double"],
    ["col38", "Long"],
    ["col39", "Symbol"],
    ["col40", "Double"]
]
designated_ts = "timestamp"

[tables.metrics10.send]
batch_pause = ["50ms", "100ms"]
batch_size = [5000, 10000]
parallel_senders = 16
tot_rows = 15_000_000
batches_connection_keepalive = 20

