debug = true

[database]
ilp = "http::addr=localhost:9000;token=qt1cBkOuvc_8VFCMHRacRaDNp7DkzTtf9Cu1eh6rSuYfMM;"
pgsql = "host=localhost port=8812 user=test_user password=pass dbname=qdb"

[tables.metrics]
schema = [
    ["timestamp", "Timestamp"],
    ["cpu_usage", "Double"],
    ["mem_free", "Long"],
    ["host", "Symbol"]
]
designated_ts = "timestamp"

[tables.metrics.send]
batch_pause = ["10ms", "100ms"]
batch_size = [10000, 50000]
parallel_senders = 16
tot_rows = 1_000_000
batches_connection_keepalive = 50

[tables.events]
schema = [
    ["event_time", "Timestamp"],
    ["event_type", "Symbol"],
    ["user_id", "Long"],
    ["details", "Symbol"]
]
designated_ts = "event_time"

[tables.events.send]
batch_pause = ["10ms", "100ms"]
batch_size = [10000, 50000]
parallel_senders = 16
tot_rows = 1_000_000
batches_connection_keepalive = 50
